### ISSUE TITLE
Error while generating project. 

### ISSUE THREAD

**Issue by parmarnishant** [RehanSaeed/ASP.NET-MVC-Boilerplate#102]
Features

HttpException Selected:<False> DefaultIsSelected:<True>
Referrer Meta Tag Selected:<True> DefaultIsSelected:<True>
Humans.txt Selected:<True> DefaultIsSelected:<True>
Search Selected:<True> DefaultIsSelected:<True>
Atom Feed Selected:<False> DefaultIsSelected:<False>
Web-App Capable Selected:<False> DefaultIsSelected:<True>
Windows 8.1 IE 11/Edge Favicon Selected:<True> DefaultIsSelected:<True>
Windows 8 IE 10 Favicon Selected:<False> DefaultIsSelected:<True>
Google TV Favicon Selected:<False> DefaultIsSelected:<True>
Android Chrome M39+ Selected:<True> DefaultIsSelected:<True>
Android Chrome M36 to M38 Favicon Selected:<True> DefaultIsSelected:<True>
Apple Mac Safari Favicon Selected:<True> DefaultIsSelected:<True>
Apple iOS Favicons Selected:<True> DefaultIsSelected:<True>
Twitter Cards Selected:<True> DefaultIsSelected:<True>
Open Graph Selected:<True> DefaultIsSelected:<True>
Author Meta Tag Selected:<True> DefaultIsSelected:<True>
Contact Page Selected:<True> DefaultIsSelected:<True>
About Page Selected:<True> DefaultIsSelected:<True>
Redirect to Canonical URL Selected:<True> DefaultIsSelected:<True>
Sitemap Selected:<True> DefaultIsSelected:<True>
Robots.txt Selected:<True> DefaultIsSelected:<True>
Glimpse Selected:<False> DefaultIsSelected:<True>
Application Insights Selected:<True> DefaultIsSelected:<False>
NWebSec Selected:<True> DefaultIsSelected:<True>
HTTPS Everywhere Selected:<True> DefaultIsSelected:<True>
CSHTML Minification (Experimental) Selected:<True> DefaultIsSelected:<False>
XML Formatter    None - True
    DataContractSerializer - False
    XmlSerializer - False
    Both - False

JSON Serializer Settings    Camel-Case (e.g. camelCase) - True
    Title-Case (e.g. TitleCase) - False

JavaScript Test Framework    Mocha - True
    Jasmine - False
    None - False

JavaScript Hint (JS-Hint) Selected:<True> DefaultIsSelected:<True>
JavaScript Code Style (JSCS) Selected:<True> DefaultIsSelected:<True>
TypeScript Selected:<True> DefaultIsSelected:<True>
Front End Framework    Bootstrap - True
    Zurb Foundation - False
    Semantic UI - False

Target Framework    .NET Core - True
    .NET Framework 4.6.1 - True

Set the package.json or bower.json package name Selected:<True> DefaultIsSelected:<True>
Set the AssemblyCopyright Selected:<True> DefaultIsSelected:<True>
Set Random Ports Selected:<True> DefaultIsSelected:<True>
Services Selected:<False> DefaultIsSelected:<True>
JavaScript Lint Selected:<False> DefaultIsSelected:<True>

Exceptions

System.AggregateException: One or more errors occurred. ---> System.IO.IOException: The directory is not empty.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Boilerplate.Wizard.Services.FileSystemService.<>c__DisplayClass13_0.<SaveAll>b__2()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Boilerplate.Wizard.Services.FileSystemService.<SaveAll>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Boilerplate.Wizard.ViewModels.MainViewModel.<AddOrRemoveFeatures>d__19.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.IO.IOException: The directory is not empty.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Boilerplate.Wizard.Services.FileSystemService.<>c__DisplayClass13_0.<SaveAll>b__2()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Boilerplate.Wizard.Services.FileSystemService.<SaveAll>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Boilerplate.Wizard.ViewModels.MainViewModel.<AddOrRemoveFeatures>d__19.MoveNext()<---

**Comment by RehanSaeed** [comment]
Thanks for reporting this issue. Based on the error, it's trying to delete a directory in the project based on your feature selections. However, it is unable to do so because something in the directory is being used. Is there anything you can think of that might have caused this?

**Comment by RehanSaeed** [comment]
Feel free to reopen this if you have more info.
