### ISSUE TITLE
Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

### ISSUE THREAD

**Issue by ctwoodwa** [RehanSaeed/ASP.NET-MVC-Boilerplate#58]
What other information can I provide?  I'm just trying to get the default project to run after creating it for the first time.
my setup:
Visual studio 2015 (update 1)
new project using the ASP.NET MVC 6(RC 1 update 1) Boilerplate(Also TC 1)
selected default project options,
restored packages, 
ran default gulp task
compiles
IE display's:
HTTP Error 502.3 - Bad Gateway

The specified CGI application encountered an error and the server terminated the process.

Visual Studio exception:
when running in IIS express or web:
Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
stack trace:
 at Proxy_From_ViewResult_To_IViewResult_3.get_StatusCode()
   at Glimpse.Agent.Internal.Inspectors.WebDiagnosticsInspector.OnBeforeActionResult(IActionContext actionContext, Object result)
   at Proxy_Method_From_<>f__AnonymousType10`2_To_Void OnBeforeActionResult(Glimpse.Agent.Internal.Inspectors.Mvc.Proxies.IActionContext, System.Object)(Object , Object , IProxyFactory )
   at Microsoft.Extensions.DiagnosticAdapter.ProxyDiagnosticSourceMethodAdapter.<>c__DisplayClass1_0.<Adapt>b__0(Object listener, Object data)
   at Microsoft.Extensions.DiagnosticAdapter.DiagnosticSourceAdapter.Write(String diagnosticName, Object parameters)
   at Microsoft.Extensions.DiagnosticAdapter.DiagnosticSourceAdapter.System.IObserver<System.Collections.Generic.KeyValuePair<System.String,System.Object>>.OnNext(KeyValuePair`2 value)
   at System.Diagnostics.DiagnosticListener.Write(String name, Object value)
   at Microsoft.AspNet.Mvc.Diagnostics.FilterActionInvokerDiagnosticSourceExtensions.BeforeActionResult(DiagnosticSource diagnosticSource, ActionContext actionContext, IActionResult result)
   at Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeResultAsync>d__56.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)

**Comment by RehanSaeed** [comment]
Have you installed the latest tools? Did you run `dnvm upgrade`? Are you trying to use full IIS (See [here](https://github.com/aspnet/Home/issues/1000)).

**Comment by RehanSaeed** [comment]
Seems to be a duplicate of https://github.com/RehanSaeed/ASP.NET-MVC-Boilerplate/issues/55.

**Comment by ctwoodwa** [comment]
Can you provide some clarification as to what you mean by latest tools?  are you referring to visual studio extensions, npm packages, or something else?

I have performed the dnvm upgrade (without a resolution) and verified there are no updates to Visual Studio 2015.  
Is there a list of tools and what versions they should be, so I can verify I have the correct version?

If i create a new web project from the asp.net Empty, Web API or Web Application they run without issue.

**Comment by ctwoodwa** [comment]
unchecking "Suppress JIT optimization on module load" solved the issue for me

Tools menu ->Options -> Debugging -> General -> Uncheck this option "Suppress JIT optimization on module load"

**Comment by RehanSaeed** [comment]
@ctwoodwa Was this an option that you had turned on? This option is unchecked for my by default in VS 2015.

**Comment by ctwoodwa** [comment]
It was checked on my install or maybe turned by an extension.  I don't remember checking it.  I do all my day job in Visual 2013 right now.

**Comment by cgatian** [comment]
Also had this checked by default.

**Comment by erwindevreugd** [comment]
I also ran into this issue when "Suppress JIT optimization on module load" is checked".
Glimps 2.0.0-beta1
MVC 6.0.0-rc1-final
DNX 4.5.1

'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\vreugd e\.dnx\packages\Microsoft.AspNet.WebUtilities\1.0.0-rc1-final\lib\net451\Microsoft.AspNet.WebUtilities.dll'. Cannot find or open the PDB file.
Exception thrown: 'System.AccessViolationException' in Glimpse.Agent.AspNet.dll
'dnx.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\WINDOWS\assembly\GAC_MSIL\Microsoft.VisualStudio.Debugger.Runtime\14.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.Debugger.Runtime.dll'. 
The program '[18540] dnx.exe' has exited with code -1073741819 (0xc0000005) 'Access violation'.
The program '[22348] iisexpress.exe' has exited with code 0 (0x0).

Unchecked "Suppress JIT optimization on module load" and Glimpse works as expected
