### ISSUE TITLE
Missing jshint and jslint

### ISSUE THREAD

**Issue by mklaber** [RehanSaeed/ASP.NET-MVC-Boilerplate#89]
I created an MVC 6 RC1 Update 1 project using extension v2.14.0 and had to manually install jshint and tslint: `npm install --save-dev jshint tslint`

Without it, gulp was throwing:

```
$ gulp --tasks-simple
module.js:340
    throw err;
    ^

Error: Cannot find module 'jshint/src/cli'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (c:\Code\Scratch\BoilerplatApp20160411\BoilerplatApp20160411\node_modules\gulp-jshint\src\extract.js:1:79)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
```

And then:

```
$ gulp --tasks-simple
module.js:340
    throw err;
    ^

Error: Cannot find module 'tslint'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (c:\Code\Scratch\BoilerplatApp20160411\BoilerplatApp20160411\node_modules\gulp-tslint\index.js:5:14)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (c:\Code\Scratch\BoilerplatApp20160411\BoilerplatApp20160411\gulpfile.js:32:14)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
```

(`gulp --tasks-simple` is what VS 2015 task runner explorer calls)

**Comment by RehanSaeed** [comment]
Looks like this dependency was added in 2.0 according to [this](https://github.com/spalger/gulp-jshint) for jshint. [tslint](https://github.com/panuhorsmalahti/gulp-tslint) also.

**Comment by RehanSaeed** [comment]
Fixed in the release later today. FYI, tslint was already being added. Just added jshint.
